language: ruby
cache:
  - bundler
  - apt
rvm:
  - 2.2.0
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
bundler_args: --quiet --jobs=3 --retry=3
# script:
  # - RAILS_ENV=test bundle exec rspec spec
